### ISSUE TITLE
logs: Cannot find module 'npm' 

### ISSUE THREAD

**Issue by killturinG** [florianf/tileoven#10]
Hello

Start tilemill with `./index.js --server=true --listenHost=0.0.0.0`
But can't add any layers !

Alert info:
> Unable to reach the local TileMill Server. Check the logs for details. If this problem persists please contact support at: http://support.mapbox.com/discussions/tilemill

Logs:
> [tilemill] Error: Cannot find module 'npm'
[tilemill]     at Function.Module._resolveFilename (module.js:325:15)
[tilemill]     at Function.Module._load (module.js:276:25)
[tilemill]     at Module.require (module.js:353:17)
[tilemill]     at require (internal/module.js:12:17)
[tilemill]     at server.updatesVersion (/home/tix/app/tileoven/servers/App.bones:144:15)
[tilemill]     at callbacks (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:272:11)
[tilemill]     at param (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:246:11)
[tilemill]     at pass (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:253:5)
[tilemill]     at Router._dispatch (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:280:5)
[tilemill]     at Object.Router.middleware [as handle] (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:45:10)
[tilemill] Error: Cannot find module 'npm'
[tilemill]     at Function.Module._resolveFilename (module.js:325:15)
[tilemill]     at Function.Module._load (module.js:276:25)
[tilemill]     at Module.require (module.js:353:17)
[tilemill]     at require (internal/module.js:12:17)
[tilemill]     at server.updatesVersion (/home/tix/app/tileoven/servers/App.bones:144:15)
[tilemill]     at callbacks (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:272:11)
[tilemill]     at param (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:246:11)
[tilemill]     at pass (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:253:5)
[tilemill]     at Router._dispatch (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:280:5)
[tilemill]     at Object.Router.middleware [as handle] (/home/tix/app/tileoven/node_modules/express/lib/router/index.js:45:10)

`node -v`
v4.4.4
`npm -v`
2.15.1

Where is the problem?

**Comment by florianf** [comment]
Sorry for the late reply, just saw the issue. Should be fixed.
