### ISSUE TITLE
Number of threads created while exporting a project

### ISSUE THREAD

**Issue by pcoder** [florianf/tileoven#11]
I wonder how does the tileoven project know how many threads to create while doing an export of a project?

From my experimentation, I found it to be 1.5 times the number of cpu cores available in the system. But that is just an empirical value. It would be great if someone could point me to the relevant resource.

BTW, I fiddled with `--concurrent` but that doesn't impact the number of threads that are created for exporting a project.

Thanks.

**Comment by florianf** [comment]
I think you're looking for this: https://github.com/florianf/tileoven/blob/master/index.js#L4
Seems to match your empirical measured value ;-)

**Comment by pcoder** [comment]
Aah thanks for that info @florianf Really appreciate it

**Comment by florianf** [comment]
Found another one that maybe relevant: https://github.com/florianf/tileoven/blob/master/commands/export.bones#L488

**Comment by pcoder** [comment]
Yes, I got that one when I was investigating `--concurrent` but that seems different to me.
