### ISSUE TITLE
Ubuntu 18.04 install

### ISSUE THREAD

**Issue by Tybion** [florianf/tileoven#16]
### Tileoven install on Ubuntu 18.04 ###

This install worked on a fresh install of Ubuntu 18.04 (Aug 2018), and was tested using the Road Trip example.

```
# Install node package manager
sudo apt-get install npm
npm -v
  3.5.2
node -v
  v8.10.0

# In your home directory, download the tileover source code ..
cd ~
git clone https://github.com/florianf/tileoven.git

# Change to the directory created by the git clone ..
cd tileoven

# Install the tileoven package
npm install

# Install most fonts used in the Road Trip example ..
sudo apt-get install ttf-mscorefonts-installer 

Run the package with nodejs ..   
./index.js 

```

Now, open up a browser on the same computer and open the URL ..
http://localhost:20009

Open the _Road Trip_ project, and wait for map data to be downloaded.
You will eventually see a zoomable road map of the USA.

### Start index.js automatically on logon ###

Run the '_Startup Applications_' app (search for 'startup').
Add a new entry with the full path to index.js as the command, for example ..

![tileoven-start](https://user-images.githubusercontent.com/4920031/44692223-42181380-aaa5-11e8-8222-8f58cc407626.png)

### Monitoring MBTiles file creation ###

The code that creates the MBTiles files is very solid.  The most likely cause of failure is running out of memory, so run '_System Monitor_' (search for 'monitor').  If the process regularly uses swap space, then add more memory to your computer if possible.

![tileoven-monitor](https://user-images.githubusercontent.com/4920031/44758015-617e7180-ab75-11e8-83df-e7c7f91eba17.png)

You will notice above that Tileoven is very good at using the full power of your hardware - utilising all available CPU cores.

**Comment by florianf** [comment]
Thanks a lot! Created a Wiki page and linked it from the HP of the repo.
