### ISSUE TITLE
No plugin panel

### ISSUE THREAD

**Issue by ecodiv** [florianf/tileoven#3]
Installed tileoven following the instructions, and it all seems to work great. Also plugins are loaded (see below). Yet, I am missing the plugin panel. Is it just not there, or does this mean something is wrong with my install?

```
./index.js
Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "updatesTime" in config file.
[tilemill] Starting in server mode.
[tilemill] Note: Unknown option "updatesVersion" in config file.
[tilemill] Note: Unknown option "updatesTime" in config file.
[tilemill] Started [Server Tile:20008].
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].
```

p.s. many thanks for making this available.

**Comment by florianf** [comment]
Hi,
sorry for the late reply, somehow I missed your comment.

Plugins were disabled in upstream, because it downloaded the NPM metadata for all modules and tried to query for tilemill plugins. This froze the whole app, so no plugins anymore, sorry.

**Comment by ecodiv** [comment]
OK, thanks for the feedback
