### ISSUE TITLE
error while installation

### ISSUE THREAD

**Issue by bung87** [florianf/tileoven#6]
It is similar with https://github.com/kosmtik/kosmtik/issues/183

node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> sqlite3@3.1.8 install /Users/bung/tileoven/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node :5.10.1
osx:10.11.5 (15F34)

**Comment by florianf** [comment]
Thanks for the report, but this seems only to be a warning. Could you upload your full npm-debug.log to pastebin?

**Comment by bung87** [comment]
the problem is the installation process gets stuck in `node-pre-gyp install --fallback-to-build`,the **mapnik** and its dependencies can`t install complete on OSX 10.11.5 .

**Comment by faaip** [comment]
Has there been any solution to this? Thanks.
