### ISSUE TITLE
Export fails.

### ISSUE THREAD

**Issue by pcoder** [florianf/tileoven#9]
When I try to export a tilemill project using the following command,

`./index.js export "all" --format=mbtiles --minzoom=0 --maxzoom=15 --metatile=16`

I get the following error

```
test@test:/home/test/gitprojects/tileoven$ ./index.js export "all" all.mbtiles --format=mbtiles --minzoom=0 --maxzoom=15 --metatile=16
Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "updatesTime" in config file.
Note: Unknown option "updates" in config file.
Note: Unknown option "profile" in config file.
Note: Unknown option "syncAccount" in config file.
Note: Unknown option "syncAccessToken" in config file.
Exporting format: mbtiles
Loading project... done.
Localizing project...[millstone] processing style 'style.mss'
[millstone] processing layer 'all'
[millstone] finished processing '/home/test/Documents/MapBox/project/all'
 done.
Rendering export
Creating new job /home/test/gitprojects/tileoven/all.export
Persisting state in /home/test/gitprojects/tileoven/all.export every minute
Writing errors to /home/test/gitprojects/tileoven/all.export-failed
[7m 17s] Part(1/1) 0.3919% 1.54m/392.90m @ 83/s | 1d 6h 55m 9s left | ✓ 2.2k ■ 0 □ 1.54m fail 0Killed
```

To give you more idea about the project, I have around 200,000 points in the project.

I am using the following version of tilemill on Fedora 23, with 8GB of ram and i7-4600U CPU @ 2.10GHz processor.

Version 0.10.2 (v0.10.1-435-g8e0b257)
Copyright © 2010-2014 Mapbox, Inc.

Is there any workaround for this?

I had a similar issue with the tilemill-project and I have reported it there [too](https://github.com/tilemill-project/tilemill/issues/2587) 

Thanks in advance and highly appreciate any response.

**Comment by pcoder** [comment]
I found the issue was related to RAM. The OS was killing the export process for exhausitng a memory beyond the capacity of the RAM and swap. I increased the swap and export went well.

Please close this issue.

**Comment by florianf** [comment]
Allright, thx for the info. The same happened to me once on ubunu.
